---
rules:
  - name: example
    kind: file
    matcher:
      name: all
      options:
        basepath: /tmp/example
    thats: []
    excepts: []
    shoulds:
      - kind: end_with
        suffix: file
      - kind: exist
      - kind: match_regex
        res: /[a-z]+/
    because: "it is an example"
  - name: makefile_exists
    kind: file
    matcher:
      name: one
      options:
        filename: /tmp/example/Makefile
    thats: []
    excepts: []
    shoulds:
      - kind: exist
    because: "it is needed to encapsulate common project operations"
